In [73]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import RobustScaler, StandardScaler
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

In [74]:
diamont_project12 = pd.read_csv('C:/Users/FVILLALOBOS/Ironhack/Challenge_old/Kata-diamantes/df_limpio.csv')
diamont_project12

city  price  carat  depth  table     x     y     z clarity  \
0       Amsterdam   6216   1.00   61.6   54.0  6.49  6.46  3.99     VS2   
1       Amsterdam    675   0.30   60.6   60.0  4.34  4.30  2.62     VS2   
2       Amsterdam   1841   0.62   61.1   59.0  5.56  5.50  3.38     VS2   
3       Amsterdam    720   0.32   60.2   57.0  4.45  4.42  2.67     VS2   
4       Amsterdam   8874   1.39   62.0   56.0  7.18  7.14  4.44     VS2   
...           ...    ...    ...    ...    ...   ...   ...   ...     ...   
40450     Antwerp   1570   0.91   67.0   62.0  5.97  5.89  3.98      I1   
40451      Madrid    992   0.70   70.8   56.0  5.38  5.33  3.79      I1   
40452      London    992   0.70   65.4   59.0  5.60  5.49  3.63      I1   
40453      London   2280   1.00   68.0   57.0  6.14  6.05  4.15      I1   
40454  Luxembourg    627   0.50   68.3   58.0  4.91  4.78  3.32      I1   

           cut color  
0      Premium     G  
1      Premium     G  
2      Premium     G  
3      Premium     G  
4      Premium     G  
...        ...   ...  
40450     Fair     F  
40451     Fair     F  
40452     Fair     F  
40453     Fair     F  
40454     Fair     F  

[40455 rows x 11 columns]

In [75]:
diamont_project12["total"] = diamont_project12["x"] * diamont_project12["x"] * diamont_project12["z"]
diamont_project12

city  price  carat  depth  table     x     y     z clarity  \
0       Amsterdam   6216   1.00   61.6   54.0  6.49  6.46  3.99     VS2   
1       Amsterdam    675   0.30   60.6   60.0  4.34  4.30  2.62     VS2   
2       Amsterdam   1841   0.62   61.1   59.0  5.56  5.50  3.38     VS2   
3       Amsterdam    720   0.32   60.2   57.0  4.45  4.42  2.67     VS2   
4       Amsterdam   8874   1.39   62.0   56.0  7.18  7.14  4.44     VS2   
...           ...    ...    ...    ...    ...   ...   ...   ...     ...   
40450     Antwerp   1570   0.91   67.0   62.0  5.97  5.89  3.98      I1   
40451      Madrid    992   0.70   70.8   56.0  5.38  5.33  3.79      I1   
40452      London    992   0.70   65.4   59.0  5.60  5.49  3.63      I1   
40453      London   2280   1.00   68.0   57.0  6.14  6.05  4.15      I1   
40454  Luxembourg    627   0.50   68.3   58.0  4.91  4.78  3.32      I1   

           cut color       total  
0      Premium     G  168.059199  
1      Premium     G   49.349272  
2      Premium     G  104.487968  
3      Premium     G   52.872675  
4      Premium     G  228.892656  
...        ...   ...         ...  
40450     Fair     F  141.850782  
40451     Fair     F  109.699276  
40452     Fair     F  113.836800  
40453     Fair     F  156.453340  
40454     Fair     F   80.038892  

[40455 rows x 12 columns]

In [76]:
X1  = diamont_project12[["carat", "depth", "table","x","y","z","total"]]
X1

carat  depth  table     x     y     z       total
0       1.00   61.6   54.0  6.49  6.46  3.99  168.059199
1       0.30   60.6   60.0  4.34  4.30  2.62   49.349272
2       0.62   61.1   59.0  5.56  5.50  3.38  104.487968
3       0.32   60.2   57.0  4.45  4.42  2.67   52.872675
4       1.39   62.0   56.0  7.18  7.14  4.44  228.892656
...      ...    ...    ...   ...   ...   ...         ...
40450   0.91   67.0   62.0  5.97  5.89  3.98  141.850782
40451   0.70   70.8   56.0  5.38  5.33  3.79  109.699276
40452   0.70   65.4   59.0  5.60  5.49  3.63  113.836800
40453   1.00   68.0   57.0  6.14  6.05  4.15  156.453340
40454   0.50   68.3   58.0  4.91  4.78  3.32   80.038892

[40455 rows x 7 columns]

In [77]:
num_scaler = StandardScaler()
diamonds_num_scaled_X1 = num_scaler.fit_transform(X1)
diamonds_num_scaled_X1

array([[ 0.42540082, -0.10675463, -1.54292407, ...,  0.63418686,
         0.64965847,  0.49746246],
       [-1.04661509, -0.80522122,  1.1434334 , ..., -1.2495849 ,
        -1.31575886, -1.04425112],
       [-0.37369353, -0.45598793,  0.69570715, ..., -0.20304503,
        -0.22545435, -0.32815198],
       ...,
       [-0.20546314,  2.54741842,  0.69570715, ..., -0.2117662 ,
         0.13319845, -0.20673651],
       [ 0.42540082,  4.36343156, -0.19974534, ...,  0.27661907,
         0.87919626,  0.34673445],
       [-0.62603911,  4.57297154,  0.24798091, ..., -0.83096895,
        -0.31153102, -0.64567785]])

In [78]:
X1 = pd.DataFrame(diamonds_num_scaled_X1)
X1

0         1         2         3         4         5         6
0      0.425401 -0.106755 -1.542924  0.676434  0.634187  0.649658  0.497462
1     -1.046615 -0.805221  1.143433 -1.235631 -1.249585 -1.315759 -1.044251
2     -0.373694 -0.455988  0.695707 -0.150646 -0.203045 -0.225454 -0.328152
3     -1.004557 -1.084608 -0.199745 -1.137805 -1.144931 -1.244028 -0.998492
4      1.245524  0.172632 -0.647472  1.290073  1.227226  1.295234  1.287521
...         ...       ...       ...       ...       ...       ...       ...
40450  0.236142  3.664965  2.038886  0.213981  0.137080  0.635312  0.157088
40451 -0.205463  6.319138 -0.647472 -0.310725 -0.351305  0.362736 -0.260472
40452 -0.205463  2.547418  0.695707 -0.115072 -0.211766  0.133198 -0.206737
40453  0.425401  4.363432 -0.199745  0.365167  0.276619  0.879196  0.346734
40454 -0.626039  4.572972  0.247981 -0.728712 -0.830969 -0.311531 -0.645678

[40455 rows x 7 columns]

In [79]:
X2 = diamont_project12[["city", "clarity", "cut","color"]]
X2

city clarity      cut color
0       Amsterdam     VS2  Premium     G
1       Amsterdam     VS2  Premium     G
2       Amsterdam     VS2  Premium     G
3       Amsterdam     VS2  Premium     G
4       Amsterdam     VS2  Premium     G
...           ...     ...      ...   ...
40450     Antwerp      I1     Fair     F
40451      Madrid      I1     Fair     F
40452      London      I1     Fair     F
40453      London      I1     Fair     F
40454  Luxembourg      I1     Fair     F

[40455 rows x 4 columns]

In [80]:
label_encoder = LabelEncoder()
for x in X2.columns:
    X2[x] = label_encoder.fit_transform(X2[x])
X2

C:\Users\FVILLALOBOS\AppData\Local\Temp\ipykernel_29504\2548041825.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X2[x] = label_encoder.fit_transform(X2[x])


city  clarity  cut  color
0         0        5    3      3
1         0        5    3      3
2         0        5    3      3
3         0        5    3      3
4         0        5    3      3
...     ...      ...  ...    ...
40450     1        0    0      2
40451     7        0    0      2
40452     5        0    0      2
40453     5        0    0      2
40454     6        0    0      2

[40455 rows x 4 columns]

In [81]:
diamonds_num_scaled_X2 = num_scaler.fit_transform(X2)
diamonds_num_scaled_X2

array([[-1.51296444,  0.67238541,  0.43492737,  0.23557324],
       [-1.51296444,  0.67238541,  0.43492737,  0.23557324],
       [-1.51296444,  0.67238541,  0.43492737,  0.23557324],
       ...,
       [-0.2002368 , -2.22618581, -2.48104657, -0.35223379],
       [-0.2002368 , -2.22618581, -2.48104657, -0.35223379],
       [ 0.06230873, -2.22618581, -2.48104657, -0.35223379]])

In [82]:
X2 = pd.DataFrame(diamonds_num_scaled_X2)
X2

0         1         2         3
0     -1.512964  0.672385  0.434927  0.235573
1     -1.512964  0.672385  0.434927  0.235573
2     -1.512964  0.672385  0.434927  0.235573
3     -1.512964  0.672385  0.434927  0.235573
4     -1.512964  0.672385  0.434927  0.235573
...         ...       ...       ...       ...
40450 -1.250419 -2.226186 -2.481047 -0.352234
40451  0.324854 -2.226186 -2.481047 -0.352234
40452 -0.200237 -2.226186 -2.481047 -0.352234
40453 -0.200237 -2.226186 -2.481047 -0.352234
40454  0.062309 -2.226186 -2.481047 -0.352234

[40455 rows x 4 columns]

In [83]:
X = pd.merge(X1, X2, left_index=True, right_index=True)
X

0_x       1_x       2_x       3_x         4         5         6  \
0      0.425401 -0.106755 -1.542924  0.676434  0.634187  0.649658  0.497462   
1     -1.046615 -0.805221  1.143433 -1.235631 -1.249585 -1.315759 -1.044251   
2     -0.373694 -0.455988  0.695707 -0.150646 -0.203045 -0.225454 -0.328152   
3     -1.004557 -1.084608 -0.199745 -1.137805 -1.144931 -1.244028 -0.998492   
4      1.245524  0.172632 -0.647472  1.290073  1.227226  1.295234  1.287521   
...         ...       ...       ...       ...       ...       ...       ...   
40450  0.236142  3.664965  2.038886  0.213981  0.137080  0.635312  0.157088   
40451 -0.205463  6.319138 -0.647472 -0.310725 -0.351305  0.362736 -0.260472   
40452 -0.205463  2.547418  0.695707 -0.115072 -0.211766  0.133198 -0.206737   
40453  0.425401  4.363432 -0.199745  0.365167  0.276619  0.879196  0.346734   
40454 -0.626039  4.572972  0.247981 -0.728712 -0.830969 -0.311531 -0.645678   

            0_y       1_y       2_y       3_y  
0     -1.512964  0.672385  0.434927  0.235573  
1     -1.512964  0.672385  0.434927  0.235573  
2     -1.512964  0.672385  0.434927  0.235573  
3     -1.512964  0.672385  0.434927  0.235573  
4     -1.512964  0.672385  0.434927  0.235573  
...         ...       ...       ...       ...  
40450 -1.250419 -2.226186 -2.481047 -0.352234  
40451  0.324854 -2.226186 -2.481047 -0.352234  
40452 -0.200237 -2.226186 -2.481047 -0.352234  
40453 -0.200237 -2.226186 -2.481047 -0.352234  
40454  0.062309 -2.226186 -2.481047 -0.352234  

[40455 rows x 11 columns]

In [84]:
y = diamont_project12[["price"]]
y

price
0       6216
1        675
2       1841
3        720
4       8874
...      ...
40450   1570
40451    992
40452    992
40453   2280
40454    627

[40455 rows x 1 columns]

In [85]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"X_train: {X_train.shape}, X_test: {X_test.shape}, y_train: {y_train.shape}, y_test: {y_test.shape}")

X_train: (32364, 11), X_test: (8091, 11), y_train: (32364, 1), y_test: (8091, 1)


In [106]:
regressor = RandomForestRegressor(random_state = 42,
                              n_estimators = 3000,
                             criterion = 'squared_error',
                             max_depth = 20,
                             oob_score = True)
hyperparameters = regressor.get_params()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

C:\Users\FVILLALOBOS\Miniconda3\envs\sklearn-env\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\FVILLALOBOS\AppData\Local\Temp\ipykernel_29504\2794606684.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(X_train, y_train)
C:\Users\FVILLALOBOS\Miniconda3\envs\sklearn-env\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [107]:
y_pred

array([2272.7427965 ,  517.05742319,  608.52794279, ..., 4307.61035331,
       1256.57816742, 5691.16821605])

In [108]:
rmse = mean_squared_error(y_pred, y_test, squared=False)
rmse

571.4465716672719

In [109]:
diamont_kaggle = pd.read_csv('C:/Users/FVILLALOBOS/Ironhack/Project_modulo3.Francisco-Villalobos-/diamonds_test.csv')
diamont_kaggle

id  carat        cut color clarity  depth  table     x     y     z  \
0          0   0.79  Very Good     F     SI1   62.7   60.0  5.82  5.89  3.67   
1          1   1.20      Ideal     J     VS1   61.0   57.0  6.81  6.89  4.18   
2          2   1.57    Premium     H     SI1   62.2   61.0  7.38  7.32  4.57   
3          3   0.90  Very Good     F     SI1   63.8   54.0  6.09  6.13  3.90   
4          4   0.50  Very Good     F     VS1   62.9   58.0  5.05  5.09  3.19   
...      ...    ...        ...   ...     ...    ...    ...   ...   ...   ...   
13480  13480   0.57      Ideal     E     SI1   61.9   56.0  5.35  5.32  3.30   
13481  13481   0.71      Ideal     I     VS2   62.2   55.0  5.71  5.73  3.56   
13482  13482   0.70      Ideal     F     VS1   61.6   55.0  5.75  5.71  3.53   
13483  13483   0.70  Very Good     F     SI2   58.8   57.0  5.85  5.89  3.45   
13484  13484   0.40      Ideal     I    VVS2   62.4   55.0  4.70  4.73  2.94   

                city  
0          Amsterdam  
1              Surat  
2           Kimberly  
3           Kimberly  
4          Amsterdam  
...              ...  
13480      Amsterdam  
13481  New York City  
13482       Tel Aviv  
13483          Surat  
13484  New York City  

[13485 rows x 11 columns]

In [110]:
X_kagle = diamont_kaggle[["carat", "depth", "table", "x", "y", "z","city","clarity","cut", "color"]]
X_kagle

carat  depth  table     x     y     z           city clarity  \
0       0.79   62.7   60.0  5.82  5.89  3.67      Amsterdam     SI1   
1       1.20   61.0   57.0  6.81  6.89  4.18          Surat     VS1   
2       1.57   62.2   61.0  7.38  7.32  4.57       Kimberly     SI1   
3       0.90   63.8   54.0  6.09  6.13  3.90       Kimberly     SI1   
4       0.50   62.9   58.0  5.05  5.09  3.19      Amsterdam     VS1   
...      ...    ...    ...   ...   ...   ...            ...     ...   
13480   0.57   61.9   56.0  5.35  5.32  3.30      Amsterdam     SI1   
13481   0.71   62.2   55.0  5.71  5.73  3.56  New York City     VS2   
13482   0.70   61.6   55.0  5.75  5.71  3.53       Tel Aviv     VS1   
13483   0.70   58.8   57.0  5.85  5.89  3.45          Surat     SI2   
13484   0.40   62.4   55.0  4.70  4.73  2.94  New York City    VVS2   

             cut color  
0      Very Good     F  
1          Ideal     J  
2        Premium     H  
3      Very Good     F  
4      Very Good     F  
...          ...   ...  
13480      Ideal     E  
13481      Ideal     I  
13482      Ideal     F  
13483  Very Good     F  
13484      Ideal     I  

[13485 rows x 10 columns]

In [111]:
X_kagle["total"] = X_kagle["x"] * X_kagle["x"] * X_kagle["z"]
X_kagle

carat  depth  table     x     y     z           city clarity  \
0       0.79   62.7   60.0  5.82  5.89  3.67      Amsterdam     SI1   
1       1.20   61.0   57.0  6.81  6.89  4.18          Surat     VS1   
2       1.57   62.2   61.0  7.38  7.32  4.57       Kimberly     SI1   
3       0.90   63.8   54.0  6.09  6.13  3.90       Kimberly     SI1   
4       0.50   62.9   58.0  5.05  5.09  3.19      Amsterdam     VS1   
...      ...    ...    ...   ...   ...   ...            ...     ...   
13480   0.57   61.9   56.0  5.35  5.32  3.30      Amsterdam     SI1   
13481   0.71   62.2   55.0  5.71  5.73  3.56  New York City     VS2   
13482   0.70   61.6   55.0  5.75  5.71  3.53       Tel Aviv     VS1   
13483   0.70   58.8   57.0  5.85  5.89  3.45          Surat     SI2   
13484   0.40   62.4   55.0  4.70  4.73  2.94  New York City    VVS2   

             cut color       total  
0      Very Good     F  124.311708  
1          Ideal     J  193.852098  
2        Premium     H  248.902308  
3      Very Good     F  144.643590  
4      Very Good     F   81.352975  
...          ...   ...         ...  
13480      Ideal     E   94.454250  
13481      Ideal     I  116.070596  
13482      Ideal     F  116.710625  
13483  Very Good     F  118.067625  
13484      Ideal     I   64.944600  

[13485 rows x 11 columns]

In [112]:
X_kagle1 = X_kagle[["carat", "depth", "table","x","y","z","total"]]
X_kagle1

carat  depth  table     x     y     z       total
0       0.79   62.7   60.0  5.82  5.89  3.67  124.311708
1       1.20   61.0   57.0  6.81  6.89  4.18  193.852098
2       1.57   62.2   61.0  7.38  7.32  4.57  248.902308
3       0.90   63.8   54.0  6.09  6.13  3.90  144.643590
4       0.50   62.9   58.0  5.05  5.09  3.19   81.352975
...      ...    ...    ...   ...   ...   ...         ...
13480   0.57   61.9   56.0  5.35  5.32  3.30   94.454250
13481   0.71   62.2   55.0  5.71  5.73  3.56  116.070596
13482   0.70   61.6   55.0  5.75  5.71  3.53  116.710625
13483   0.70   58.8   57.0  5.85  5.89  3.45  118.067625
13484   0.40   62.4   55.0  4.70  4.73  2.94   64.944600

[13485 rows x 7 columns]

In [113]:
diamonds_num_scaled_kagle_X1 = num_scaler.fit_transform(X_kagle1)
diamonds_num_scaled_kagle_X1

array([[-0.01841187,  0.66950043,  1.12187438, ...,  0.13323602,
         0.17309121, -0.07441722],
       [ 0.85507765, -0.51495701, -0.21919161, ...,  1.01939517,
         0.87078717,  0.83786229],
       [ 1.64334867,  0.3211306 ,  1.56889637, ...,  1.40044361,
         1.40431938,  1.56004947],
       ...,
       [-0.21015347, -0.09691321, -1.1132356 , ..., -0.02627263,
        -0.01843317, -0.17413354],
       [-0.21015347, -2.04778429, -0.21919161, ...,  0.13323602,
        -0.12787567, -0.15633147],
       [-0.84929214,  0.46047853, -1.1132356 , ..., -0.89470861,
        -0.82557163, -0.85323649]])

In [114]:
X3 = pd.DataFrame(diamonds_num_scaled_kagle_X1)
X3

0         1         2         3         4         5         6
0     -0.018412  0.669500  1.121874  0.075022  0.133236  0.173091 -0.074417
1      0.855078 -0.514957 -0.219192  0.964007  1.019395  0.870787  0.837862
2      1.643349  0.321131  1.568896  1.475847  1.400444  1.404319  1.560049
3      0.215939  1.435914 -1.560258  0.317472  0.345914  0.487738  0.192311
4     -0.636246  0.808848  0.227830 -0.616411 -0.575691 -0.483564 -0.637980
...         ...       ...       ...       ...       ...       ...       ...
13480 -0.487114  0.112109 -0.666214 -0.347022 -0.371875 -0.333080 -0.466108
13481 -0.188849  0.321131 -1.113236 -0.023755 -0.008549  0.022608 -0.182530
13482 -0.210153 -0.096913 -1.113236  0.012164 -0.026273 -0.018433 -0.174134
13483 -0.210153 -2.047784 -0.219192  0.101960  0.133236 -0.127876 -0.156331
13484 -0.849292  0.460479 -1.113236 -0.930699 -0.894709 -0.825572 -0.853236

[13485 rows x 7 columns]

In [115]:
X4 = diamont_kaggle[["city", "clarity", "cut","color"]]
X4

city clarity        cut color
0          Amsterdam     SI1  Very Good     F
1              Surat     VS1      Ideal     J
2           Kimberly     SI1    Premium     H
3           Kimberly     SI1  Very Good     F
4          Amsterdam     VS1  Very Good     F
...              ...     ...        ...   ...
13480      Amsterdam     SI1      Ideal     E
13481  New York City     VS2      Ideal     I
13482       Tel Aviv     VS1      Ideal     F
13483          Surat     SI2  Very Good     F
13484  New York City    VVS2      Ideal     I

[13485 rows x 4 columns]

In [116]:
for x in X4.columns:
    X4[x] = label_encoder.fit_transform(X4[x])
X4

C:\Users\FVILLALOBOS\AppData\Local\Temp\ipykernel_29504\698987086.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X4[x] = label_encoder.fit_transform(X4[x])


city  clarity  cut  color
0         0        2    4      2
1        10        4    2      6
2         3        2    3      4
3         3        2    4      2
4         0        4    4      2
...     ...      ...  ...    ...
13480     0        2    2      1
13481     8        5    2      5
13482    11        4    2      2
13483    10        3    4      2
13484     8        7    2      5

[13485 rows x 4 columns]

In [117]:
diamonds_num_scaled_kagle_X2 = num_scaler.fit_transform(X4)
diamonds_num_scaled_kagle_X2

array([[-1.51680235, -1.05624309,  1.41126057, -0.34052962],
       [ 1.10575092,  0.10435484, -0.54122212,  2.0116496 ],
       [-0.73003637, -1.05624309,  0.43501923,  0.83555999],
       ...,
       [ 1.36800625,  0.10435484, -0.54122212, -0.34052962],
       [ 1.10575092, -0.47594413,  1.41126057, -0.34052962],
       [ 0.58124026,  1.84525173, -0.54122212,  1.4236048 ]])

In [118]:
X4 = pd.DataFrame(diamonds_num_scaled_kagle_X2)
X4

0         1         2         3
0     -1.516802 -1.056243  1.411261 -0.340530
1      1.105751  0.104355 -0.541222  2.011650
2     -0.730036 -1.056243  0.435019  0.835560
3     -0.730036 -1.056243  1.411261 -0.340530
4     -1.516802  0.104355  1.411261 -0.340530
...         ...       ...       ...       ...
13480 -1.516802 -1.056243 -0.541222 -0.928574
13481  0.581240  0.684654 -0.541222  1.423605
13482  1.368006  0.104355 -0.541222 -0.340530
13483  1.105751 -0.475944  1.411261 -0.340530
13484  0.581240  1.845252 -0.541222  1.423605

[13485 rows x 4 columns]

In [119]:
X_kagle = pd.merge(X3, X4, left_index=True, right_index=True)
X_kagle

0_x       1_x       2_x       3_x         4         5         6  \
0     -0.018412  0.669500  1.121874  0.075022  0.133236  0.173091 -0.074417   
1      0.855078 -0.514957 -0.219192  0.964007  1.019395  0.870787  0.837862   
2      1.643349  0.321131  1.568896  1.475847  1.400444  1.404319  1.560049   
3      0.215939  1.435914 -1.560258  0.317472  0.345914  0.487738  0.192311   
4     -0.636246  0.808848  0.227830 -0.616411 -0.575691 -0.483564 -0.637980   
...         ...       ...       ...       ...       ...       ...       ...   
13480 -0.487114  0.112109 -0.666214 -0.347022 -0.371875 -0.333080 -0.466108   
13481 -0.188849  0.321131 -1.113236 -0.023755 -0.008549  0.022608 -0.182530   
13482 -0.210153 -0.096913 -1.113236  0.012164 -0.026273 -0.018433 -0.174134   
13483 -0.210153 -2.047784 -0.219192  0.101960  0.133236 -0.127876 -0.156331   
13484 -0.849292  0.460479 -1.113236 -0.930699 -0.894709 -0.825572 -0.853236   

            0_y       1_y       2_y       3_y  
0     -1.516802 -1.056243  1.411261 -0.340530  
1      1.105751  0.104355 -0.541222  2.011650  
2     -0.730036 -1.056243  0.435019  0.835560  
3     -0.730036 -1.056243  1.411261 -0.340530  
4     -1.516802  0.104355  1.411261 -0.340530  
...         ...       ...       ...       ...  
13480 -1.516802 -1.056243 -0.541222 -0.928574  
13481  0.581240  0.684654 -0.541222  1.423605  
13482  1.368006  0.104355 -0.541222 -0.340530  
13483  1.105751 -0.475944  1.411261 -0.340530  
13484  0.581240  1.845252 -0.541222  1.423605  

[13485 rows x 11 columns]

In [121]:
prediccon_16 = regressor.predict(X_kagle)

C:\Users\FVILLALOBOS\Miniconda3\envs\sklearn-env\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [122]:
predicciones_16 = pd.DataFrame(prediccon_16).rename(columns = {0:'price'})
predicciones_16.index.names = ['id']
predicciones_16

price
id                
0      3035.406176
1      5343.043676
2      9984.034904
3      4045.437675
4      1705.618715
...            ...
13480  1917.046978
13481  2315.788195
13482  2920.124220
13483  2177.758743
13484   826.150611

[13485 rows x 1 columns]

In [123]:
predicciones_16 = predicciones_16.to_csv('predicciones_16.csv')